# Version: V_20260710_1235_PUBSPEC_DEEPLINK
name: iran_erbil_app
description: "Iran Erbil Mobile Application Wrapper"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  url_launcher: ^6.2.5
  app_links: ^6.0.1             # 💡 اضافه شدن موتور مدیریت پیوندهای عمیق تلگرام

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
    - assets/offline.html

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash.png"
  android: true
  ios: true